name: HTTPBin API Collection
version: 1.0.0
description: "Collection for testing HTTP requests using HTTPBin"

# Base URL from variable set
base_url: "${variables.api.url}"

# Variable set configuration
variable_sets:
  - name: params
    description: "Request parameters for testing"
    defaultValue: "default"
    activeValue: "default"
    values:
      default:
        delay: 2
        status: 200
        uuid: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        bytes: 1024

# Authentication configuration
authentication:
  type: bearer
  token: "${variables.auth.token}"

# Requests in this collection
requests:
  - id: get-request
    name: "GET Request"
    description: "Simple GET request to HTTPBin"
    method: GET
    path: "/get"
    headers:
      Accept: "application/json"
      X-Custom-Header: "SHC Demo"
    query:
      foo: "bar"
      baz: "qux"
  
  - id: post-request
    name: "POST Request"
    description: "POST request with JSON body"
    method: POST
    path: "/post"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body:
      type: "json"
      content: |
        {
          "name": "SHC Demo",
          "version": "1.0.0",
          "features": ["HTTP Client", "Collections", "Variable Sets"]
        }
  
  - id: put-request
    name: "PUT Request"
    description: "PUT request with JSON body"
    method: PUT
    path: "/put"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body:
      type: "json"
      content: |
        {
          "id": 1,
          "name": "Updated Resource",
          "timestamp": "${Date.now()}"
        }
  
  - id: delete-request
    name: "DELETE Request"
    description: "DELETE request"
    method: DELETE
    path: "/delete"
    headers:
      Accept: "application/json"
  
  - id: status-code
    name: "Status Code"
    description: "Get specific status code"
    method: GET
    path: "/status/${variables.params.status}"
    headers:
      Accept: "application/json"
  
  - id: delay-request
    name: "Delayed Response"
    description: "Response with specified delay"
    method: GET
    path: "/delay/${variables.params.delay}"
    headers:
      Accept: "application/json"
  
  - id: stream-bytes
    name: "Stream Bytes"
    description: "Stream random bytes"
    method: GET
    path: "/stream-bytes/${variables.params.bytes}"
    headers:
      Accept: "application/octet-stream"
  
  - id: basic-auth
    name: "Basic Auth"
    description: "Test basic authentication"
    method: GET
    path: "/basic-auth/${variables.auth.username}/${variables.auth.password}"
    headers:
      Accept: "application/json"
    authentication:
      type: "basic"
      username: "${variables.auth.username}"
      password: "${variables.auth.password}"
  
  - id: bearer-auth
    name: "Bearer Auth"
    description: "Test bearer token authentication"
    method: GET
    path: "/bearer"
    headers:
      Accept: "application/json"
      Authorization: "Bearer ${variables.auth.token}"
  
  - id: cookies
    name: "Cookies"
    description: "Get and set cookies"
    method: GET
    path: "/cookies"
    headers:
      Accept: "application/json"
    cookies:
      session: "abc123"
      user: "john_doe"
