name: JSONPlaceholder API Collection
version: 1.0.0
description: "Collection for testing REST API operations using JSONPlaceholder"

# Base URL from variable set
base_url: "${variables.api.url}"

# Variable set configuration
variable_sets:
  - name: resource
    description: "Resource identifiers for testing"
    defaultValue: "default"
    activeValue: "default"
    values:
      default:
        userId: 1
        postId: 1
        commentId: 1
        albumId: 1
        photoId: 1
        todoId: 1
        username: "Bret"

# Variable set overrides
variable_set_overrides:
  api: "jsonplaceholder"

# Requests in this collection
requests:
  - id: get-posts
    name: "Get All Posts"
    description: "Retrieve all posts"
    method: GET
    path: "/posts"
    headers:
      Accept: "application/json"
  
  - id: get-post
    name: "Get Single Post"
    description: "Retrieve a specific post by ID"
    method: GET
    path: "/posts/${variables.resource.postId}"
    headers:
      Accept: "application/json"
  
  - id: get-post-comments
    name: "Get Post Comments"
    description: "Retrieve comments for a specific post"
    method: GET
    path: "/posts/${variables.resource.postId}/comments"
    headers:
      Accept: "application/json"
  
  - id: create-post
    name: "Create Post"
    description: "Create a new post"
    method: POST
    path: "/posts"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body:
      type: "json"
      content: |
        {
          "title": "SHC Demo Post",
          "body": "This is a test post created using SHC",
          "userId": ${variables.resource.userId}
        }
  
  - id: update-post
    name: "Update Post"
    description: "Update an existing post"
    method: PUT
    path: "/posts/${variables.resource.postId}"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body:
      type: "json"
      content: |
        {
          "id": ${variables.resource.postId},
          "title": "Updated Post Title",
          "body": "This post has been updated using SHC",
          "userId": ${variables.resource.userId}
        }
  
  - id: patch-post
    name: "Patch Post"
    description: "Partially update an existing post"
    method: PATCH
    path: "/posts/${variables.resource.postId}"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body:
      type: "json"
      content: |
        {
          "title": "Patched Post Title"
        }
  
  - id: delete-post
    name: "Delete Post"
    description: "Delete an existing post"
    method: DELETE
    path: "/posts/${variables.resource.postId}"
    headers:
      Accept: "application/json"
  
  - id: get-users
    name: "Get All Users"
    description: "Retrieve all users"
    method: GET
    path: "/users"
    headers:
      Accept: "application/json"
  
  - id: get-user
    name: "Get Single User"
    description: "Retrieve a specific user by ID"
    method: GET
    path: "/users/${variables.resource.userId}"
    headers:
      Accept: "application/json"
  
  - id: get-user-by-username
    name: "Get User by Username"
    description: "Retrieve a user by username"
    method: GET
    path: "/users"
    headers:
      Accept: "application/json"
    query:
      username: "${variables.resource.username}"
  
  - id: get-user-todos
    name: "Get User Todos"
    description: "Retrieve todos for a specific user"
    method: GET
    path: "/users/${variables.resource.userId}/todos"
    headers:
      Accept: "application/json"
  
  - id: get-user-albums
    name: "Get User Albums"
    description: "Retrieve albums for a specific user"
    method: GET
    path: "/users/${variables.resource.userId}/albums"
    headers:
      Accept: "application/json"
  
  - id: get-album-photos
    name: "Get Album Photos"
    description: "Retrieve photos for a specific album"
    method: GET
    path: "/albums/${variables.resource.albumId}/photos"
    headers:
      Accept: "application/json"
